"""add_company_product

Revision ID: 337ea87962d5
Revises: 55fb7ad5d992
Create Date: 2026-04-15 23:07:17.118432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337ea87962d5'
down_revision: Union[str, Sequence[str], None] = '55fb7ad5d992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=True)
    op.create_index(op.f('ix_companies_tax_id'), 'companies', ['tax_id'], unique=True)
    op.create_index(op.f('ix_companies_trade_name'), 'companies', ['trade_name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('company_products',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bought_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('support_until', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_products_company_id_companies')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_company_products_product_id_products')),
    sa.PrimaryKeyConstraint('company_id', 'product_id', name=op.f('pk_company_products'))
    )
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_company_id_companies'), 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_company_id_companies'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_table('company_products')
    op.drop_table('products')
    op.drop_index(op.f('ix_companies_trade_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
