"""add_password_management

Revision ID: 55fb7ad5d992
Revises: c6b8dc939d80
Create Date: 2026-04-03 01:10:17.770923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fb7ad5d992'
down_revision: Union[str, Sequence[str], None] = 'c6b8dc939d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('reset', 'invite', name='token_purpose'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_terms_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('terms_version', sa.String(length=16), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_terms_acceptances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_terms_acceptances'))
    )
    op.create_index(op.f('ix_user_terms_acceptances_terms_version'), 'user_terms_acceptances', ['terms_version'], unique=False)
    op.create_index(op.f('ix_user_terms_acceptances_user_id'), 'user_terms_acceptances', ['user_id'], unique=False)
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('must_accept_terms', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_accept_terms')
    op.drop_column('users', 'must_change_password')
    op.drop_index(op.f('ix_user_terms_acceptances_user_id'), table_name='user_terms_acceptances')
    op.drop_index(op.f('ix_user_terms_acceptances_terms_version'), table_name='user_terms_acceptances')
    op.drop_table('user_terms_acceptances')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
