"""add_file_objects

Revision ID: a6e80aba25a6
Revises: 14eee043999d
Create Date: 2026-05-24 21:47:46.390921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e80aba25a6'
down_revision: Union[str, Sequence[str], None] = '14eee043999d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=63), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('context', sa.Enum('live_chat_message', 'user_avatar', name='file_context'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'failed', 'deleted', name='file_status'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_file_objects_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_objects')),
    sa.UniqueConstraint('object_key', name=op.f('uq_file_objects_object_key'))
    )
    op.create_index(op.f('ix_file_objects_context'), 'file_objects', ['context'], unique=False)
    op.create_index('ix_file_objects_context_uploaded_at', 'file_objects', ['context', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_file_objects_status'), 'file_objects', ['status'], unique=False)
    op.create_index('ix_file_objects_status_created_at', 'file_objects', ['status', 'created_at'], unique=False)
    op.create_index('ix_file_objects_status_deleted_at', 'file_objects', ['status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_file_objects_uploaded_by_user_id'), 'file_objects', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_objects_uploaded_by_user_id'), table_name='file_objects')
    op.drop_index('ix_file_objects_status_deleted_at', table_name='file_objects')
    op.drop_index('ix_file_objects_status_created_at', table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_status'), table_name='file_objects')
    op.drop_index('ix_file_objects_context_uploaded_at', table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_context'), table_name='file_objects')
    op.drop_table('file_objects')
    # ### end Alembic commands ###
