"""drop unique constraint on file_objects object_key

Revision ID: cca8b6c18070
Revises: a6e80aba25a6
Create Date: 2026-05-25 07:45:11.835518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca8b6c18070'
down_revision: Union[str, Sequence[str], None] = 'a6e80aba25a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_file_objects_object_key'), 'file_objects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_file_objects_object_key'), 'file_objects', ['object_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
