"""add avatar_file_id to users

Revision ID: dd164affd8d5
Revises: cca8b6c18070
Create Date: 2026-05-25 18:43:54.171145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd164affd8d5'
down_revision: Union[str, Sequence[str], None] = 'cca8b6c18070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_file_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_users_avatar_file_id_file_objects'), 'users', 'file_objects', ['avatar_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_avatar_file_id_file_objects'), 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_file_id')
    # ### end Alembic commands ###
