"""cria_tabelas_empresas_e_produtos

Revision ID: ebe6c4a057ea
Revises: 337ea87962d5
Create Date: 2026-05-02 15:44:54.130435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe6c4a057ea'
down_revision: Union[str, Sequence[str], None] = '337ea87962d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
